version: '3.8'

services:
  app:
    build: .
    container_name: toshiro-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - toshiro-net

  db:
    image: mysql:5.7
    container_name: toshiro-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: toshirodb
      MYSQL_USER: toshiro
      MYSQL_PASSWORD: toshiropassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - toshiro-net

volumes:
  db_data:

networks:
  toshiro-net:
    driver: bridge

